### ISSUE TITLE
Image compression takes too long on Web

### ISSUE THREAD

**Issue by behzodfaiziev** [alann-maulana/image_compression_flutter#2]
I tried to compress web image using the below code, however it takes about 1 minute to compress a 6 mb image.
Is the function, I'm using for a web compression, a correct one?
If yes, is it because of web limitations it takes such a long time to compress?

```
Future<Uint8List?> compressImage(Uint8List imgBytes,
    {required String path, int quality = 70}) async {
 final input = ImageFile(
    rawBytes: imgBytes,
    filePath: path,
  );
  Configuration config = Configuration(
    outputType: ImageOutputType.jpg,
    // can only be true for Android and iOS while using ImageOutputType.jpg or ImageOutputType.pngÏ
    useJpgPngNativeCompressor: false,
    // set quality between 0-100
    quality: quality,
  );
  final param = ImageFileConfiguration(input: input, config: config);
  final output = await compressor.compress(param);
  return output.rawBytes;
}
```
Thank you!

**Comment by alann-maulana** [comment]
Yeah it is the expected behavior for now. Somehow compressing image process on flutter web can make your application unresponsive. You can move the image compression logic to your server, or just use it at flutter mobile and desktop application.

**Comment by behzodfaiziev** [comment]
@alann-maulana  Thanks for your advice! 
I hope this feature will be improved in the future.

**Comment by behzodfaiziev** [comment]
@alann-maulana I found a solution for compressing web image. Image picker now has XFile type which can be directly compressed in web. It took about 2 seconds to compress a 12mb image to 50kb
``` 
 final XFile? pickedImageFile = await ImagePicker().pickImage(
        source: isCamera ? ImageSource.camera : ImageSource.gallery,
        imageQuality: imageQuality,
        maxWidth: maxWidth,
        preferredCameraDevice: CameraDevice.rear);

**Comment by rulefahd** [comment]
any update ?

still freezes the whole web

**Comment by eugenio-d-tesio** [comment]
updates?

**Comment by alann-maulana** [comment]
> @alann-maulana I found a solution for compressing web image. Image picker now has XFile type which can be directly compressed in web. It took about 2 seconds to compress a 12mb image to 50kb
> 
> ```
>  final XFile? pickedImageFile = await ImagePicker().pickImage(
>         source: isCamera ? ImageSource.camera : ImageSource.gallery,
>         imageQuality: imageQuality,
>         maxWidth: maxWidth,
>         preferredCameraDevice: CameraDevice.rear); 
> ```

You can use @behzodfaiziev workaround by passing `imageQuality` along with `maxWidth` and `maxHeight` when picking image
