### ISSUE TITLE
i cant export android studio because of this

### ISSUE THREAD

**Issue by rulefahd** [alann-maulana/image_compression_flutter#5]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':image_compression_flutter' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by Harsh1052** [comment]
I am also facing same error. But there are other package [flutter_image_compress](https://pub.dev/packages/flutter_image_compress). Which is updated and you will not face Kotlin version error.
